name: evently
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  build_runner:
  flutter_gen_runner:
  flutter_svg:

  flutter_lints: ^6.0.0

flutter_gen:
  output: lib/core/gen/ 

  # Optional
  integrations:
    image: true
    flutter_svg: true

flutter:
  uses-material-design: true
  assets:
     - assets/images/
     - assets/icons/
  fonts:
     - family: Poppins
       fonts:
         - asset: assets\fonts\Poppins-Bold.ttf
         - asset: assets\fonts\Poppins-MediumItalic.ttf
         - asset: assets\fonts\Poppins-Regular.ttf
         - asset: assets\fonts\Poppins-SemiBold.ttf

dev_dependencies:
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/Ror.png"